sudo: false
language: generic
cache:
  directories:
  - $HOME/.stack
addons:
  apt:
    packages:
      - libgmp-dev
env:
- ARGS=""
- ARGS="--resolver nightly-2017-09-10"
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal --install-ghc $ARGS test --only-dependencies
script:
- stack --no-terminal test --haddock --no-haddock-deps $ARGS

