/home/ben/bin-dist-7.10.3b-Linux/ghc-7.10.3b/inplace/lib/bin/haddock -B/home/ben/bin-dist-7.10.3b-Linux/ghc-7.10.3b/inplace/lib -l/home/ben/bin-dist-7.10.3b-Linux/ghc-7.10.3b/inplace/lib --odir=libraries/process/dist-install/doc/html/process --no-tmp-comp-dir --dump-interface=libraries/process/dist-install/doc/html/process/process.haddock --html --hoogle --title=process-1.2.3.0: Process libraries --prologue=libraries/process/dist-install/haddock-prologue.txt --read-interface=../base-4.8.2.0,../base-4.8.2.0/src/%{MODULE/./-}.html#%{NAME},libraries/base/dist-install/doc/html/base/base.haddock --read-interface=../deepseq-1.4.1.1,../deepseq-1.4.1.1/src/%{MODULE/./-}.html#%{NAME},libraries/deepseq/dist-install/doc/html/deepseq/deepseq.haddock --read-interface=../directory-1.2.2.0,../directory-1.2.2.0/src/%{MODULE/./-}.html#%{NAME},libraries/directory/dist-install/doc/html/directory/directory.haddock --read-interface=../filepath-1.4.0.0,../filepath-1.4.0.0/src/%{MODULE/./-}.html#%{NAME},libraries/filepath/dist-install/doc/html/filepath/filepath.haddock --read-interface=../unix-2.7.1.0,../unix-2.7.1.0/src/%{MODULE/./-}.html#%{NAME},libraries/unix/dist-install/doc/html/unix/unix.haddock --optghc=-hisuf --optghc=dyn_hi --optghc=-osuf --optghc=dyn_o --optghc=-hcsuf --optghc=dyn_hc --optghc=-fPIC --optghc=-dynamic --optghc=-H32m --optghc=-O --optghc=-this-package-key --optghc=proce_52AgREEfSrnJLlkGV9YZZJ --optghc=-hide-all-packages --optghc=-i --optghc=-ilibraries/process/. --optghc=-ilibraries/process/dist-install/build --optghc=-ilibraries/process/dist-install/build/autogen --optghc=-Ilibraries/process/dist-install/build --optghc=-Ilibraries/process/dist-install/build/autogen --optghc=-Ilibraries/process/include --optghc=-optP-include --optghc=-optPlibraries/process/dist-install/build/autogen/cabal_macros.h --optghc=-package-key --optghc=base_HQfYBxpPvuw8OunzQu6JGM --optghc=-package-key --optghc=deeps_6vMKxt5sPFR0XsbRWvvq59 --optghc=-package-key --optghc=direc_0hFG6ZxK1nk4zsyOqbNHfm --optghc=-package-key --optghc=filep_Ey7a1in9roBAE8bUFJ5R9m --optghc=-package-key --optghc=unix_KZL8h98IqDM57kQSPo1mKx --optghc=-Wall --optghc=-XHaskell2010 --optghc=-O2 --optghc=-no-user-package-db --optghc=-rtsopts --optghc=-odir --optghc=libraries/process/dist-install/build --optghc=-hidir --optghc=libraries/process/dist-install/build --optghc=-stubdir --optghc=libraries/process/dist-install/build --source-module=src/%{MODULE/./-}.html --source-entity=src/%{MODULE/./-}.html#%{NAME} libraries/process/./System/Cmd.hs libraries/process/dist-install/build/System/Process.hs libraries/process/./System/Process/Internals.hs +RTS -tlibraries/process/dist-install/doc/html/process/process.haddock.t --machine-readable 
 [("bytes allocated", "589325872")
 ,("num_GCs", "770")
 ,("average_bytes_used", "22488245")
 ,("max_bytes_used", "61431016")
 ,("num_byte_usage_samples", "7")
 ,("peak_megabytes_allocated", "126")
 ,("init_cpu_seconds", "0.004")
 ,("init_wall_seconds", "0.001")
 ,("mutator_cpu_seconds", "0.180")
 ,("mutator_wall_seconds", "0.217")
 ,("GC_cpu_seconds", "0.312")
 ,("GC_wall_seconds", "0.332")
 ]
